---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

<!-- # Useage -->

<!-- To run a set of scenarios for Alameda county, you'd run the same code as the non-package version of LEMMA-Forecasts: -->

<!-- ```{r,eval=FALSE} -->
<!-- library(LEMMA.forecasts) -->

<!-- writedir <- normalizePath("~/Desktop/tmp/") -->
<!-- county.dt <- GetCountyData(remote = TRUE) -->
<!-- max.date <- Get1(county.dt[!is.na(hosp.conf), max(date), by = "county"]$V1) -->
<!-- cat("max date = ", as.character(max.date), "\n") -->

<!-- doses.dt <- GetDosesData(remote = TRUE) -->

<!-- county.by.pop <- unique(county.dt[!is.na(population), .(county, population)]) #NA population if no hospitalizations -->
<!-- setorder(county.by.pop, -population) -->
<!-- county.set <- county.by.pop[, county] -->

<!-- county.set <- setdiff(county.set, "Colusa"); cat("excluding Colusa\n") -->
<!-- print(county.set) -->

<!-- # scenario-specific functions are appended with `_scen`, minor difference from other code -->
<!-- RunOneCounty_scen(county1 = "Alameda",county.dt = county.dt,doses.dt = doses.dt,remote = TRUE,writedir = writedir) -->
<!-- ``` -->


# LEMMA.forecasts

This package provides functions to run forecasts (`LEMMA.forecasts::RunOneCounty`) or scenarios (`LEMMA.forecasts::RunOneCounty_scen`) using the [LEMMA model](https://localepi.github.io/LEMMA/). These functions are used in the LEMMA [Shiny app](https://localepi.shinyapps.io/LEMMA-Shiny/). Please see the vignette for an example of how to use the package.

Within the `R/` directory the code is organized as:

  1. `GenerateEmail.R`
      1. `GenerateEmail`
  1. `GetCountyData_Scenario.R`
      1. `GetCountyInputs_scen`
      2. `Scenario`
      3. `GetResults_scen`
  2. `GetCountyData.R`
      1. `GetCountyData`
      2. `GetStateData`
      3. `ReadCsvAWS`
      4. `ConvertNegative`
      5. `GetOldAdmits`
      6. `GetAdmits`
      7. `GetAdmits_notused`
      8. `GetSantaClaraData`
  3. `GetCountyInputs.R`
      1. `Get1`
      2. `GetCountySheets`
      3. `GetCountyInputs`
  4. `GetDosesData.R`
      1. `GetDosesData.old`
      2. `GetDosesData`
      3. `ReadSFDoses.old`
      4. `SFDosesToAWS`
      5. `ReadSFDoses`
  5. `RunCounty_Scenario.R`
      1. `RunOneCounty_scen`
      2. `RunOneCounty_scen_input`
  6. `RunCounty.R`
      1. `RunOneCounty`
  7. `CreateStateOverview.R`
      1. `CreateOverview`
      2. `RtMap`
